# Introduction to Numpy

In [1]:
import numpy as np

### Compare Python List and NumPy Array

In [4]:
import time

In [8]:
x = list(range(100000))
y = list(range(100000))

In [9]:
start = time.time()
z = []
for i in range(len(x)):
    Z.append(x[i] + y[i])
    
end = time.time()
end - start

0.047284841537475586

In [10]:
X = np.array(x)
Y = np.array(y)

In [11]:
start = time.time()
Z = X + Y
end = time.time()

end - start

0.023600339889526367

### Shape, Size and Data Type of an Array

In [12]:
Z.size

100000

In [16]:
type(Z)

numpy.ndarray

In [13]:
Z.dtype

dtype('int32')

In [14]:
Z.shape

(100000,)

In [15]:
Z.ndim

1

### Creating Basic NumPy Arrays

In [17]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.linspace(start=17, stop=31, num=50)

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

### Add, Remove and Sort

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [35]:
arr = np.append(arr, 15)
arr

array([ 1,  2,  3,  4,  5,  6, 15])

In [36]:
arr = np.delete(arr, 1)
arr

array([ 1,  3,  4,  5,  6, 15])

In [37]:
np.sort(arr)

array([ 1,  3,  4,  5,  6, 15])

### Reshaping an Array

In [38]:
np.reshape(arr, (2, 3))

array([[ 1,  3,  4],
       [ 5,  6, 15]])

In [39]:
arr.reshape(2, 3)

array([[ 1,  3,  4],
       [ 5,  6, 15]])

### quiz

In [52]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]
arr = np.array(L)
arr.sort()
arr = np.delete(arr, 4)
arr

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [70]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]
arr = np.array(L)
arr = np.append(arr, 53)
arr = arr.reshape(2, 7)
arr

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])

In [59]:
arr[0:3, 1:4]

array([[ 2,  7,  8],
       [13, 46, 23]])

In [60]:
arr[-1, -2]

41

In [71]:
arr = np.append(arr, 40)
arr = arr.reshape(5, 3)
arr

array([[10,  2,  7],
       [ 8,  3, 22],
       [54, 12, 13],
       [46, 23, 25],
       [41, 53, 40]])

In [72]:
arr[0:3:2]

array([[10,  2,  7],
       [54, 12, 13]])

### quiz

In [78]:
# Use the NumPy library to create an array (say arr) of the first 25 (exclusive) integers starting from 0
arr = np.arange(25)

# Reshape the array into shape (5, 5).
arr = arr.reshape(5, 5) 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
# Select the elements present in first two rows (i.e. row 0 and row 1) and last two columns (i.e. column 3 and column 4)
arr[0:2, -2:]

array([[3, 4],
       [8, 9]])

In [90]:
# From the array created in question 1 (i.e. 5 x 5 array), 
# select all the elements at evenly positioned columns and oddly positioned rows.
# Use stride concept here
arr[1::2, 0::2]

array([[ 5,  7,  9],
       [15, 17, 19]])